name: Static Analysis
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run lint

    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run build

    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - run: bun install
            - name: Run tests
              run: bun test --coverage --coverage-reporter=lcov
            - name: Report code coverage
              uses: zgosalvez/github-actions-report-lcov@v4
              with:
                coverage-files: coverage/lcov.*.info
                artifact-name: code-coverage-report
                github-token: ${{ secrets.GITHUB_TOKEN }}
                working-directory: ./src
                update-comment: true
